# Generated by Django 3.0.5 on 2020-04-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
