# Generated by Django 3.0.5 on 2020-04-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_videolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolink',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
