# Generated by Django 3.0.5 on 2020-04-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_videolink_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='article_body',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
