# Generated by Django 3.0.5 on 2020-04-29 15:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20200429_1106'),
    ]

    operations = []
