# Generated by Django 3.0.5 on 2020-04-29 16:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200429_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_body_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_body',
            field=models.TextField(max_length=2500, null=True),
        ),
    ]
