# Generated by Django 3.0.5 on 2020-04-29 16:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20200429_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_body_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
