# Generated by Django 3.0.5 on 2020-04-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_remove_article_article_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_body',
        ),
    ]
